# -*- coding: utf-8 -*-
"""Despliegue videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJ34YjvOT3ZSWyT_8fJSioyI-mZydB5i
"""

# Despliegue

#- Cargamos el modelo
#- Cargamos los datos futuros
#- Preparar los datos futuros
#- Aplicamos el modelo para la predicción

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo.pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

#interfaz grafica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st
import pandas as pd

st.title('Predicción basada en edad y tipo de carro')

# Controles de entrada
age = st.slider('Edad', min_value=0, max_value=100, value=20, step=1)
cartype = st.selectbox('Tipo de Carro', ['combi', 'sport', 'family'])

# Crear DataFrame
datos = [[age, cartype]]
data = pd.DataFrame(datos, columns=['age', 'cartype'])

# Mostrar los datos capturados
st.subheader('Datos capturados:')
st.dataframe(data)

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red
#En los despliegues no se llama fit
data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
data_preparada.head()

"""# Predicciones

El modelo presenta un error del 9%
"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#predicciones finales
data